theme: jekyll-theme-midnight
title: dropClust
description: Efficient clustering of droplet-based single cell RNA-seq datasets
site_name: dropClust
site.github.repository_url: https://github.com/debsin/dropClust
github:
  repository_url: https://github.com/debsin/dropClust
